import { ContentItem, Elements } from "@kentico/kontent-delivery";

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Product extends ContentItem {
  public price: Elements.NumberElement;
  public description: Elements.TextElement;
  public photo: Elements.AssetsElement;
  public name: Elements.TextElement;
  public productCategories: Elements.TaxonomyElement;
  constructor() {
    super({
      propertyResolver: (elementName: string) => {
        if (elementName === "product_categories") {
          return "productCategories";
        }
        return elementName;
      },
    });
  }
}
